## This NoteBook Structure:
1. Load Data
2. Merge Required Tables
3. Convert Date
4. Time-Based Split
5. Missing Value Handling
6. Feature Engineering
7. Encoding
8. Final Dataset
9. Save Processed Data

## 1. Load Data

In [7]:
import numpy as np
import pandas as pd
from pathlib import Path
DATA_PATH = Path("../data/raw")

In [8]:
train_df = pd.read_csv(DATA_PATH / "train.csv")
stores_df = pd.read_csv(DATA_PATH / "stores.csv")
holidays_df = pd.read_csv(DATA_PATH / "holidays_events.csv")
oil_df = pd.read_csv(DATA_PATH / "oil.csv")
transactions_df = pd.read_csv(DATA_PATH / "transactions.csv")

In [9]:
## Convert Date Immediatly
train_df["date"] = pd.to_datetime(train_df["date"])
oil_df["date"] = pd.to_datetime(oil_df["date"])
transactions_df["date"] = pd.to_datetime(transactions_df["date"])
holidays_df["date"] = pd.to_datetime(holidays_df["date"])

## 2. Merge Required Tables

In [10]:
# Merge Store Information
df = train_df.merge(
    stores_df,
    on="store_nbr",
    how="left"
)

In [13]:
## Merge Transaction
df = df.merge(
    transactions_df,
    on=["date","store_nbr"],
    how="left"
)

In [17]:
oil_df.head()

        date  dcoilwtico
0 2013-01-01         NaN
1 2013-01-02       93.14
2 2013-01-03       92.97
3 2013-01-04       93.12
4 2013-01-07       93.20

In [15]:
## Merge Oil Prices
df = df.merge(
    oil_df,
    on="date",
    how="left"
)

In [16]:
df.head()

,id,date,store_nbr,family,sales,onpromotion,city,state,type,cluster,transactions,dcoilwtico
0,0,2013-01-01,1,AUTOMOTIVE,0.0,0,Quito,Pichincha,D,13,NaN,NaN
1,1,2013-01-01,1,BABY CARE,0.0,0,Quito,Pichincha,D,13,NaN,NaN
2,2,2013-01-01,1,BEAUTY,0.0,0,Quito,Pichincha,D,13,NaN,NaN
3,3,2013-01-01,1,BEVERAGES,0.0,0,Quito,Pichincha,D,13,NaN,NaN
4,4,2013-01-01,1,BOOKS,0.0,0,Quito,Pichincha,D,13,NaN,NaN

In [18]:
## Merge Holidays Information
df = df.merge(
    holidays_df,
    on="date",
    how="left"
)

In [19]:
print(df.shape)
df.head()

(3054348, 17)

,id,date,store_nbr,family,sales,onpromotion,city,state,type_x,cluster,transactions,dcoilwtico,type_y,locale,locale_name,description,transferred
0,0,2013-01-01,1,AUTOMOTIVE,0.0,0,Quito,Pichincha,D,13,NaN,NaN,Holiday,National,Ecuador,Primer dia del ano,False
1,1,2013-01-01,1,BABY CARE,0.0,0,Quito,Pichincha,D,13,NaN,NaN,Holiday,National,Ecuador,Primer dia del ano,False
2,2,2013-01-01,1,BEAUTY,0.0,0,Quito,Pichincha,D,13,NaN,NaN,Holiday,National,Ecuador,Primer dia del ano,False
3,3,2013-01-01,1,BEVERAGES,0.0,0,Quito,Pichincha,D,13,NaN,NaN,Holiday,National,Ecuador,Primer dia del ano,False
4,4,2013-01-01,1,BOOKS,0.0,0,Quito,Pichincha,D,13,NaN,NaN,Holiday,National,Ecuador,Primer dia del ano,False

## 3. Sort the DATA

In [20]:
df.head()

,id,date,store_nbr,family,sales,onpromotion,city,state,type_x,cluster,transactions,dcoilwtico,type_y,locale,locale_name,description,transferred
0,0,2013-01-01,1,AUTOMOTIVE,0.0,0,Quito,Pichincha,D,13,NaN,NaN,Holiday,National,Ecuador,Primer dia del ano,False
1,1,2013-01-01,1,BABY CARE,0.0,0,Quito,Pichincha,D,13,NaN,NaN,Holiday,National,Ecuador,Primer dia del ano,False
2,2,2013-01-01,1,BEAUTY,0.0,0,Quito,Pichincha,D,13,NaN,NaN,Holiday,National,Ecuador,Primer dia del ano,False
3,3,2013-01-01,1,BEVERAGES,0.0,0,Quito,Pichincha,D,13,NaN,NaN,Holiday,National,Ecuador,Primer dia del ano,False
4,4,2013-01-01,1,BOOKS,0.0,0,Quito,Pichincha,D,13,NaN,NaN,Holiday,National,Ecuador,Primer dia del ano,False

In [21]:
df = df.sort_values(
    by=["store_nbr","family","date"]
).reset_index(drop=True)

In [22]:
df.head()

,id,date,store_nbr,family,sales,onpromotion,city,state,type_x,cluster,transactions,dcoilwtico,type_y,locale,locale_name,description,transferred
0,0,2013-01-01,1,AUTOMOTIVE,0.0,0,Quito,Pichincha,D,13,NaN,NaN,Holiday,National,Ecuador,Primer dia del ano,False
1,1782,2013-01-02,1,AUTOMOTIVE,2.0,0,Quito,Pichincha,D,13,2111.0,93.14,NaN,NaN,NaN,NaN,NaN
2,3564,2013-01-03,1,AUTOMOTIVE,3.0,0,Quito,Pichincha,D,13,1833.0,92.97,NaN,NaN,NaN,NaN,NaN
3,5346,2013-01-04,1,AUTOMOTIVE,3.0,0,Quito,Pichincha,D,13,1863.0,93.12,NaN,NaN,NaN,NaN,NaN
4,7128,2013-01-05,1,AUTOMOTIVE,5.0,0,Quito,Pichincha,D,13,1509.0,NaN,Work Day,National,Ecuador,Recupero puente Navidad,False

In [26]:
df.shape

(3054348, 17)

In [28]:
df.isnull().sum().sort_values(ascending=False)

locale          2551824
type_y          2551824
locale_name     2551824
description     2551824
transferred     2551824
dcoilwtico       955152
transactions     249117
id                    0
date                  0
type_x                0
state                 0
city                  0
onpromotion           0
sales                 0
family                0
store_nbr             0
cluster               0
dtype: int64

## 4. Time Based Feature Engineering

In [29]:
df.head()

,id,date,store_nbr,family,sales,onpromotion,city,state,type_x,cluster,transactions,dcoilwtico,type_y,locale,locale_name,description,transferred
0,0,2013-01-01,1,AUTOMOTIVE,0.0,0,Quito,Pichincha,D,13,NaN,NaN,Holiday,National,Ecuador,Primer dia del ano,False
1,1782,2013-01-02,1,AUTOMOTIVE,2.0,0,Quito,Pichincha,D,13,2111.0,93.14,NaN,NaN,NaN,NaN,NaN
2,3564,2013-01-03,1,AUTOMOTIVE,3.0,0,Quito,Pichincha,D,13,1833.0,92.97,NaN,NaN,NaN,NaN,NaN
3,5346,2013-01-04,1,AUTOMOTIVE,3.0,0,Quito,Pichincha,D,13,1863.0,93.12,NaN,NaN,NaN,NaN,NaN
4,7128,2013-01-05,1,AUTOMOTIVE,5.0,0,Quito,Pichincha,D,13,1509.0,NaN,Work Day,National,Ecuador,Recupero puente Navidad,False

In [30]:
df["year"] = df["date"].dt.year

In [32]:
df["month"] = df["date"].dt.month

In [33]:
df["day"] = df["date"].dt.day

In [34]:
df["day_of_week"] = df["date"].dt.dayofweek

In [35]:
df.head()

,id,date,store_nbr,family,sales,onpromotion,city,state,type_x,cluster,...,dcoilwtico,type_y,locale,locale_name,description,transferred,year,month,day,day_of_week
0,0,2013-01-01,1,AUTOMOTIVE,0.0,0,Quito,Pichincha,D,13,...,NaN,Holiday,National,Ecuador,Primer dia del ano,False,2013,1,1,1
1,1782,2013-01-02,1,AUTOMOTIVE,2.0,0,Quito,Pichincha,D,13,...,93.14,NaN,NaN,NaN,NaN,NaN,2013,1,2,2
2,3564,2013-01-03,1,AUTOMOTIVE,3.0,0,Quito,Pichincha,D,13,...,92.97,NaN,NaN,NaN,NaN,NaN,2013,1,3,3
3,5346,2013-01-04,1,AUTOMOTIVE,3.0,0,Quito,Pichincha,D,13,...,93.12,NaN,NaN,NaN,NaN,NaN,2013,1,4,4
4,7128,2013-01-05,1,AUTOMOTIVE,5.0,0,Quito,Pichincha,D,13,...,NaN,Work Day,National,Ecuador,Recupero puente Navidad,False,2013,1,5,5

In [36]:
df['day'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
      dtype=int32)

In [37]:
df["day_of_week"].unique()

array([1, 2, 3, 4, 5, 6, 0], dtype=int32)

In [38]:
df["day_name"] = df["date"].dt.day_name()

In [40]:
df["is_weekend"] = (df["day_of_week"]>=5).astype(int)

In [43]:
df['is_weekend'].unique()

array([0, 1])

In [44]:
df["quarter"] = df["date"].dt.quarter

In [45]:
df["week_of_year"] = (df["date"].dt.isocalendar().week.astype(int))

In [51]:
df["day_of_year"] = (df["date"].dt.dayofyear)

In [52]:
df["is_month_start"] = (df["date"].dt.is_month_start.astype(int))

In [53]:
df["is_month_end"] = (df["date"].dt.is_month_end.astype(int))

In [54]:
new_features = [
    "date",
    "year",
    "month",
    "day",
    "day_of_week",
    "day_name",
    "week_of_year",
    "day_of_year",
    "quarter",
    "is_weekend",
    "is_month_start",
    "is_month_end"
]

df[new_features].head(10)

,date,year,month,day,day_of_week,day_name,week_of_year,day_of_year,quarter,is_weekend,is_month_start,is_month_end
0,2013-01-01,2013,1,1,1,Tuesday,1,1,1,0,1,0
1,2013-01-02,2013,1,2,2,Wednesday,1,2,1,0,0,0
2,2013-01-03,2013,1,3,3,Thursday,1,3,1,0,0,0
3,2013-01-04,2013,1,4,4,Friday,1,4,1,0,0,0
4,2013-01-05,2013,1,5,5,Saturday,1,5,1,1,0,0
5,2013-01-06,2013,1,6,6,Sunday,1,6,1,1,0,0
6,2013-01-07,2013,1,7,0,Monday,2,7,1,0,0,0
7,2013-01-08,2013,1,8,1,Tuesday,2,8,1,0,0,0
8,2013-01-09,2013,1,9,2,Wednesday,2,9,1,0,0,0
9,2013-01-10,2013,1,10,3,Thursday,2,10,1,0,0,0

In [55]:
df[new_features].isnull().sum()

date              0
year              0
month             0
day               0
day_of_week       0
day_name          0
week_of_year      0
day_of_year       0
quarter           0
is_weekend        0
is_month_start    0
is_month_end      0
dtype: int64

## Lag Features
A lag feature is simply:

A previous value of the target variable used as an input feature.

In [ ]:
df["lag_1"] = (df.groupby(["store_nbr", "family"])["sales"].shift(1))   #shift=1 means  1 day ago

In [57]:
df.head()

,id,date,store_nbr,family,sales,onpromotion,city,state,type_x,cluster,...,day_name,is_wwekend,is_weekend,quarter,week_of_year,day-of_year,is_month_start,is_month_end,day_of_year,lag_1
0,0,2013-01-01,1,AUTOMOTIVE,0.0,0,Quito,Pichincha,D,13,...,Tuesday,0,0,1,1,1,1,0,1,NaN
1,1782,2013-01-02,1,AUTOMOTIVE,2.0,0,Quito,Pichincha,D,13,...,Wednesday,0,0,1,1,2,0,0,2,0.0
2,3564,2013-01-03,1,AUTOMOTIVE,3.0,0,Quito,Pichincha,D,13,...,Thursday,0,0,1,1,3,0,0,3,2.0
3,5346,2013-01-04,1,AUTOMOTIVE,3.0,0,Quito,Pichincha,D,13,...,Friday,0,0,1,1,4,0,0,4,3.0
4,7128,2013-01-05,1,AUTOMOTIVE,5.0,0,Quito,Pichincha,D,13,...,Saturday,1,1,1,1,5,0,0,5,3.0

In [59]:
## Why groupby()?
'''
Without it, the last sale of one product family could become the previous sale of another product family.

That would produce incorrect features.

Grouping ensures each store-family history is treated independently.
'''

'\nWithout it, the last sale of one product family could become the previous sale of another product family.\n\nThat would produce incorrect features.\n\nGrouping ensures each store-family history is treated independently.\n'

In [60]:
df["lag_7"] = (
    df
    .groupby(["store_nbr", "family"])["sales"]
    .shift(7)
)

In [61]:
df["lag_14"] = (
    df
    .groupby(["store_nbr", "family"])["sales"]
    .shift(14)
)

In [63]:
df["lag_28"] = (
    df
    .groupby(["store_nbr", "family"])["sales"]
    .shift(28)
)

In [64]:
cols = [
    "date",
    "store_nbr",
    "family",
    "sales",
    "lag_1",
    "lag_7",
    "lag_14",
    "lag_28"
]

df[cols].head(20)

         date  store_nbr      family  sales  lag_1  lag_7  lag_14  lag_28
0  2013-01-01          1  AUTOMOTIVE    0.0    NaN    NaN     NaN     NaN
1  2013-01-02          1  AUTOMOTIVE    2.0    0.0    NaN     NaN     NaN
2  2013-01-03          1  AUTOMOTIVE    3.0    2.0    NaN     NaN     NaN
3  2013-01-04          1  AUTOMOTIVE    3.0    3.0    NaN     NaN     NaN
4  2013-01-05          1  AUTOMOTIVE    5.0    3.0    NaN     NaN     NaN
5  2013-01-06          1  AUTOMOTIVE    2.0    5.0    NaN     NaN     NaN
6  2013-01-07          1  AUTOMOTIVE    0.0    2.0    NaN     NaN     NaN
7  2013-01-08          1  AUTOMOTIVE    2.0    0.0    0.0     NaN     NaN
8  2013-01-09          1  AUTOMOTIVE    2.0    2.0    2.0     NaN     NaN
9  2013-01-10          1  AUTOMOTIVE    2.0    2.0    3.0     NaN     NaN
10 2013-01-11          1  AUTOMOTIVE    3.0    2.0    3.0     NaN     NaN
11 2013-01-12          1  AUTOMOTIVE    2.0    3.0    5.0     NaN     NaN
12 2013-01-13          1  AUTOMOTIVE    2.0    2.0    2.0     NaN     NaN
13 2013-01-14          1  AUTOMOTIVE    2.0    2.0    0.0     NaN     NaN
14 2013-01-15          1  AUTOMOTIVE    1.0    2.0    2.0     0.0     NaN
15 2013-01-16          1  AUTOMOTIVE    1.0    1.0    2.0     2.0     NaN
16 2013-01-17          1  AUTOMOTIVE    1.0    1.0    2.0     3.0     NaN
17 2013-01-18          1  AUTOMOTIVE    0.0    1.0    3.0     3.0     NaN
18 2013-01-19          1  AUTOMOTIVE    5.0    0.0    2.0     5.0     NaN
19 2013-01-20          1  AUTOMOTIVE    3.0    5.0    2.0     2.0     NaN

In [65]:
lag_cols = [
    "lag_1",
    "lag_7",
    "lag_14",
    "lag_28"
]

df[lag_cols].isnull().sum()

lag_1      1782
lag_7     12474
lag_14    24948
lag_28    49896
dtype: int64

## Rolling Window Features

In [66]:
df["rolling_mean_7"] = (
    df
    .groupby(["store_nbr", "family"])["sales"]
    .transform(
        lambda x: x.shift(1).rolling(window=7).mean()
    )
)

In [67]:
df["rolling_mean_14"] = (
    df
    .groupby(["store_nbr", "family"])["sales"]
    .transform(
        lambda x: x.shift(1).rolling(14).mean()
    )
)

In [68]:
df["rolling_mean_28"] = (
    df
    .groupby(["store_nbr", "family"])["sales"]
    .transform(
        lambda x: x.shift(1).rolling(28).mean()
    )
)

In [69]:
df["rolling_std_7"] = (
    df
    .groupby(["store_nbr", "family"])["sales"]
    .transform(
        lambda x: x.shift(1).rolling(7).std()
    )
)

In [70]:
df["rolling_max_7"] = (
    df
    .groupby(["store_nbr", "family"])["sales"]
    .transform(
        lambda x: x.shift(1).rolling(7).max()
    )
)

In [71]:
df["rolling_min_7"] = (
    df
    .groupby(["store_nbr", "family"])["sales"]
    .transform(
        lambda x: x.shift(1).rolling(7).min()
    )
)

In [72]:
rolling_cols = [
    "sales",
    "lag_1",
    "rolling_mean_7",
    "rolling_mean_14",
    "rolling_mean_28",
    "rolling_std_7",
    "rolling_max_7",
    "rolling_min_7"
]

df[rolling_cols].head(20)

,sales,lag_1,rolling_mean_7,rolling_mean_14,rolling_mean_28,rolling_std_7,rolling_max_7,rolling_min_7
0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
3,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN
5,2.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN
6,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
7,2.0,0.0,2.142857,NaN,NaN,1.772811,5.0,0.0
8,2.0,2.0,2.428571,NaN,NaN,1.511858,5.0,0.0
9,2.0,2.0,2.428571,NaN,NaN,1.511858,5.0,0.0
10,3.0,2.0,2.285714,NaN,NaN,1.496026,5.0,0.0
11,2.0,3.0,2.285714,NaN,NaN,1.496026,5.0,0.0
12,2.0,2.0,1.857143,NaN,NaN,0.899735,3.0,0.0
13,2.0,2.0,1.857143,NaN,NaN,0.899735,3.0,0.0
14,1.0,2.0,2.142857,2.142857,NaN,0.377964,3.0,2.0
15,1.0,1.0,2.000000,2.214286,NaN,0.577350,3.0,1.0
16,1.0,1.0,1.857143,2.142857,NaN,0.690066,3.0,1.0
17,0.0,1.0,1.714286,2.000000,NaN,0.755929,3.0,1.0
18,5.0,0.0,1.285714,1.785714,NaN,0.755929,2.0,0.0
19,3.0,5.0,1.714286,1.785714,NaN,1.603567,5.0,0.0

## Expanding window Features

In [73]:
df["expanding_mean"] = (
    df
    .groupby(["store_nbr", "family"])["sales"]
    .transform(
        lambda x: x.shift(1).expanding().mean()
    )
)

In [74]:
df["expanding_std"] = (
    df
    .groupby(["store_nbr", "family"])["sales"]
    .transform(
        lambda x: x.shift(1).expanding().std()
    )
)

In [75]:
df["expanding_max"] = (
    df
    .groupby(["store_nbr", "family"])["sales"]
    .transform(
        lambda x: x.shift(1).expanding().max()
    )
)

In [76]:
df["expanding_min"] = (
    df
    .groupby(["store_nbr", "family"])["sales"]
    .transform(
        lambda x: x.shift(1).expanding().min()
    )
)

In [77]:
cols = [
    "sales",
    "expanding_mean",
    "expanding_std",
    "expanding_max",
    "expanding_min"
]

df[cols].head(20)

    sales  expanding_mean  expanding_std  expanding_max  expanding_min
0     0.0             NaN            NaN            NaN            NaN
1     2.0        0.000000            NaN            0.0            0.0
2     3.0        1.000000       1.414214            2.0            0.0
3     3.0        1.666667       1.527525            3.0            0.0
4     5.0        2.000000       1.414214            3.0            0.0
5     2.0        2.600000       1.816590            5.0            0.0
6     0.0        2.500000       1.643168            5.0            0.0
7     2.0        2.142857       1.772811            5.0            0.0
8     2.0        2.125000       1.642081            5.0            0.0
9     2.0        2.111111       1.536591            5.0            0.0
10    3.0        2.100000       1.449138            5.0            0.0
11    2.0        2.181818       1.401298            5.0            0.0
12    2.0        2.166667       1.337116            5.0            0.0
13    2.0        2.153846       1.281025            5.0            0.0
14    1.0        2.142857       1.231456            5.0            0.0
15    1.0        2.066667       1.222799            5.0            0.0
16    1.0        2.000000       1.211060            5.0            0.0
17    0.0        1.941176       1.197424            5.0            0.0
18    5.0        1.833333       1.248529            5.0            0.0
19    3.0        2.000000       1.414214            5.0            0.0